micronaut:
  application:
    name: customer
  security:
    token:
      jwt:
        signatures:
          jwks:
            auth0:
              url: '${OAUTH_JWKS:`https://dev-lpjdaef2.us.auth0.com/.well-known/jwks.json`}'

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    dialect: org.hibernate.dialect.PostgreSQLDialect
    maximum-pool-size: 1


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages: 'org.agilemonkeys.customer.persistence.entity'

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      table: customers_flyway_schema_history
