create table customers
(
    id           bigserial generated by default as identity,
    name         varchar(100) not null,
    surname      varchar(100) not null,
    document_id  varchar(30)  not null,
    created_date timestamp    not null,
    created_by   varchar(100),
    updated_date timestamp,
    updated_by   varchar(100),

    primary key (id)
);
